window.prompts =
[ // u9f1 u9f1 speculating
	{text:"Your co-worker Omar wants to know about the time required to set up a new drilling operation. Tell Omar the range. Use the table to help you.",
	audio: "g1",
	image: "1.png"},
	{text:"Your co-worker Eman wants to know about the production rate of oil wells. Tell Eman the range. Use the table to help you.",
	audio: "g2",
	image: "2.png"},
	{text:"Your new co-worker Yasser wants to know how long communication meetings last. Tell Yasser the range. Use the table to help you.",
	audio: "g3",
	image: "3.png"},
	{text:"Your co-worker Nada asks you about the project costs. Tell Nada the range. Use the table to help you.",
	audio: "g4",
	image: "4.png"},
	{text:"Your co-worker Mohamed asks you how long it takes to write reports. Tell Mohamed the range. Use the table to help you.",
	audio: "g5",
	image: "5.png"},
	{text:"Your co-worker Mona asks you about the number of employees in each department. Tell Mona the range. Use the table to help you.",
	audio: "g6",
	image: "6.png"},
	{text:"Your co-worker Ibrahim asks you about the amount of water required to put out an industrial fire. Tell Ibrahim the range. Use the table to help you.",
	audio: "g7",
	image: "7.png"},
	{text:"Your co-worker Nouf asks you about the humidity range. Tell her. Use the table to help you.",
	audio: "g8",
	image: "8.png"},
	{text:"The pressure in the reservoir is 1,000 PSI. You are not sure if this is safe. Ask your co-worker Adel about the safe range.",
	audio: "g9",
	image: ""},
	{text:"The gas concentration level is 5%. You are not sure if this is acceptable. Ask your co-worker Mubarak about the acceptable range.",
	audio: "g10",
	image: ""},
	
]
